"""Robustness checks for the local NK channel index.

These are deliberately light-weight checks for the theory manuscript.  They do
not claim to exhaust the parameter space.  They ask whether the qualitative
prediction--a local channel estimate improves prediction of future realised
improvement--survives changes in system size, stabilisation margin and proposal
breadth/noise settings.
"""
from __future__ import annotations

from pathlib import Path
import sys
from dataclasses import replace

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR))

from nk_channel_simulation import AgentParameters
from nk_local_channel_index import (
    ChannelSamplingParameters,
    run_channel_grid,
    add_future_gains,
    prediction_table,
    set_nature_like_style,
)


def one_scenario(label: str, N: int, reps: int, params: AgentParameters, channel_samples: int, seed_offset: int) -> pd.DataFrame:
    cp = ChannelSamplingParameters(n_channel_samples=channel_samples, horizons=(1, 3, 5, 10))
    K_values = (0, 4, 8, 10) if N <= 12 else (0, 4, 8, 12)
    D_values = (2, 4, 8)
    traj, local = run_channel_grid(N=N, K_values=K_values, D_values=D_values, reps=reps, steps=40, seed=20260611 + seed_offset, params=params, channel_params=cp)
    lf = add_future_gains(traj, local, cp.horizons)
    pred = prediction_table(lf, cp.horizons)
    pred["scenario"] = label
    pred["N"] = N
    pred["reps"] = reps
    pred["channel_samples"] = channel_samples
    pred["margin_lambda"] = params.channel_margin_lambda
    pred["n_model_proposals"] = params.n_model_proposals
    pred["model_bias_strength"] = params.model_bias_strength
    # Correlation of local index with h=5 gain, independent of the linear model.
    corr = float(lf[["local_channel_index", "future_gain_h5"]].dropna().corr().iloc[0, 1])
    pred["corr_index_gain_h5"] = corr
    return pred


def summarise_robustness(pred_all: pd.DataFrame) -> pd.DataFrame:
    wide = pred_all.pivot_table(index=["scenario", "N", "margin_lambda", "n_model_proposals", "model_bias_strength", "channel_samples", "reps", "corr_index_gain_h5"], columns=["horizon", "model"], values="r2_test")
    rows = []
    for idx, row in wide.iterrows():
        d = dict(zip(["scenario", "N", "margin_lambda", "n_model_proposals", "model_bias_strength", "channel_samples", "reps", "corr_index_gain_h5"], idx))
        for h in (1, 3, 5, 10):
            base = row[(h, "baseline")]
            ind = row[(h, "baseline_plus_index")]
            chan = row[(h, "baseline_plus_channel")]
            rows.append({**d, "horizon": h, "r2_baseline": base, "r2_index": ind, "r2_channel": chan, "delta_r2_index": ind - base, "delta_r2_channel": chan - base})
    return pd.DataFrame(rows)


def plot_robustness(summary: pd.DataFrame, outdir: Path) -> None:
    set_nature_like_style()
    h5 = summary[summary["horizon"] == 5].copy().sort_values("scenario")
    x = np.arange(len(h5))
    fig, ax = plt.subplots(figsize=(7.2, 2.6))
    width = 0.32
    ax.bar(x - width/2, h5["delta_r2_index"], width=width, label=r"+ $A^{NK}_t$")
    ax.bar(x + width/2, h5["delta_r2_channel"], width=width, label="+ channel terms")
    ax.axhline(0, color="black", linewidth=0.6)
    ax.set_xticks(x, labels=h5["scenario"], rotation=25, ha="right")
    ax.set_ylabel(r"Gain in test $R^2$ at $h=5$")
    ax.set_title("Robustness of local-channel prediction", loc="left", pad=2)
    ax.legend(frameon=False, ncol=2, loc="upper left", handlelength=1.2)
    for spine in ax.spines.values():
        spine.set_linewidth(0.6)
    fig.tight_layout()
    fig.savefig(outdir / "extended_data_fig_robustness.pdf")
    fig.savefig(outdir / "extended_data_fig_robustness.png", dpi=450)
    plt.close(fig)


def write_numbers(summary: pd.DataFrame, outpath: Path) -> None:
    h5 = summary[summary["horizon"] == 5]
    min_idx = float(h5["delta_r2_index"].min())
    min_chan = float(h5["delta_r2_channel"].min())
    max_idx = float(h5["delta_r2_index"].max())
    max_chan = float(h5["delta_r2_channel"].max())
    mean_corr = float(h5["corr_index_gain_h5"].mean())
    text = f"""% Automatically generated by nk_robustness_checks.py
\\newcommand{{\\NKRobustMinIndexGain}}{{{min_idx:.3f}}}
\\newcommand{{\\NKRobustMaxIndexGain}}{{{max_idx:.3f}}}
\\newcommand{{\\NKRobustMinChannelGain}}{{{min_chan:.3f}}}
\\newcommand{{\\NKRobustMaxChannelGain}}{{{max_chan:.3f}}}
\\newcommand{{\\NKRobustMeanCorr}}{{{mean_corr:.3f}}}
"""
    outpath.write_text(text)


def main() -> None:
    base = Path(__file__).resolve().parents[1]
    data_dir = base / "data"
    outdir = base / "extended_data"
    data_dir.mkdir(exist_ok=True)
    outdir.mkdir(exist_ok=True)

    # Keep reps moderate. These are sensitivity checks, not the main simulation.
    scenarios = [
        ("default", 16, AgentParameters(), 32, 0),
        ("stricter margin", 16, replace(AgentParameters(), channel_margin_lambda=1.00), 32, 10),
        ("lenient margin", 16, replace(AgentParameters(), channel_margin_lambda=0.35), 32, 20),
        ("smaller state", 12, AgentParameters(), 32, 30),
        ("more model proposals", 16, replace(AgentParameters(), n_model_proposals=20), 32, 40),
    ]
    pred_all = []
    for label, N, params, samples, seed_offset in scenarios:
        print(f"Running {label}...")
        pred_all.append(one_scenario(label, N=N, reps=8, params=params, channel_samples=samples, seed_offset=seed_offset))
    pred_all = pd.concat(pred_all, ignore_index=True)
    summary = summarise_robustness(pred_all)
    pred_all.to_csv(data_dir / "nk_robustness_prediction_raw.csv", index=False)
    summary.to_csv(data_dir / "nk_robustness_summary.csv", index=False)
    plot_robustness(summary, outdir)
    write_numbers(summary, base / "nk_robustness_numbers.tex")
    print(summary[summary.horizon == 5].to_string(index=False))


if __name__ == "__main__":
    main()
